# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install build tools
RUN apk add --no-cache python3 build-base

# Copy only package files and typescript config
COPY package.json pnpm-lock.yaml tsconfig.json ./

# Copy source
COPY src ./src

# Install dependencies and build
RUN npm install && npm run build

# Default command
CMD ["node", "dist/index.js"]
